### PR TITLE
Fixed #1564 Clip job cancel for multiple jobs fixed

### LINKED ISSUE #1564: data cleanup if error occurs
ui companion ticket for https://github.com/ngageoint/hootenanny/issues/3270

### PR DESCRIPTION
**Pull request by bobi7**
ref #1564

### CODE REVIEW

File: modules/Hoot/ui/modals/importDataset.js [hunk 1]
```diff
@@ -369,11 +369,17 @@ export default class ImportDataset {
...
                 let message;
                 if (resp.data && resp.data.status === 'cancelled') {
                     message = 'Import job cancelled';
 
+                    // Delete the newly created folder
+                    if ( newFolderName ) {
+                        await Hoot.api.deleteFolder( folderId );
+                        await Hoot.folders.removeFolder( folderId );
+                    }
+
```
Comment (brianhatchl) [inline modules/Hoot/ui/modals/importDataset.js:382]: We talked about how this would be better done within the services.  If we moved folder creation to within a job command we could have that occur after successful clipping and if it was canceled the new output folder would never be created so we would not have to clean it up at all.  However, the services don't have a mechanism for passing input between job commands, so the folder id created by the AddFolder command would not be available to the UpdateParent command that moves output maps underneath said folder.
So we'll keep this way for now as it should run immediately after canceling.

**Review by brianhatchl — APPROVED** [review]
Looks good, I actually thought this was adding Cancel for multi-import, but I can do that next and will create a ticket.

**Comment by brianhatchl** [comment]
I see it's already there #1563

File: modules/Hoot/ui/modals/importDataset.js (hunk 1 above)
Comment (bobi7) [reply modules/Hoot/ui/modals/importDataset.js:382]: Note: moved this to https://github.com/ngageoint/hootenanny/issues/3412
