### PR TITLE
fixed #1668. fixed bug with pressing enter with replace dropdown open

### LINKED ISSUE #1668: unexpected changeset replace behavior
if you open the dropdown for changeset replace and you press enter instead of selecting an option the job gets run and it doesnt appear to auto select the item in the dropdown either

steps:
grail pull
click changeset replace button in jobs panel
click to open the dropdown but dont select anything. instead press enter

### PR DESCRIPTION
**Pull request by bobi7**
ref #1668

### CODE REVIEW

File: modules/Hoot/ui/modals/grailDatasetPicker.js [hunk 1]
```diff
@@ -27,7 +27,6 @@ export default class GrailDatasetPicker {
                     readonly: 'readonly',
                     sort: false,
                     itemKey: 'name',
-                    _value: this.layer.id,
```
Comment (brianhatchl) [inline modules/Hoot/ui/modals/grailDatasetPicker.js:30]: How come you removed this?  `_value` is the hack to provide the combobox with a value that differs from the option label.

Comment (bobi7) [reply modules/Hoot/ui/modals/grailDatasetPicker.js:30]: it was giving it a default value which would be the layer itself so when you open the combobox and press enter, even though you didnt select an option it would go to the submit function call, retrieve the _value, and get that default.

The combobox still looks the same as far as I can see

**Review by brianhatchl — APPROVED** [review]
