### PR TITLE
do not allow undefined in hash, make hash match loadedLayers state

### LINKED ISSUE #1472: url shows undefined=*some id* when dataset added from datasets panel
I have seen this show up randomly but one way to reproduce this: go to datasets panel -> right click dataset and add it are secondary -> undefined will show up in url

### PR DESCRIPTION
**Pull request by maxgrossman**
closes #1472

### CODE REVIEW

File: modules/Hoot/managers/layerManager.js [hunk 1]
```diff
@@ -287,16 +303,21 @@ export default class Layers {
                 input2Name = tags.input2Name;
 
             if ( (input1 && input1Name) && (input2 && input2Name) ) {
-                let params1 = {
-                    name: input1Name,
-                    id: input1,
-                    color: 'violet'
-                };
+                let loaded = Object.values(Hoot.layers.loadedLayers).find(l => l.id === tags.input1),
```
Comment (maxgrossman) [inline modules/Hoot/managers/layerManager.js]: This was where the undefined problem was occurring during the review,

Comment (maxgrossman) [reply modules/Hoot/managers/layerManager.js]: Since the params did not include a refType, then this gets passed to loadLayer, which tries to update hash using params.refType, but without checking if params.refType is undefined.
