### PR TITLE
Fixed #1900. fixed issue with import multiple not able to take prj file

### LINKED ISSUE #1900: prj files cant be imported on import multiple
When doing import multiple shapefiles, the .prj file gets greyed out and so the import fails

### PR DESCRIPTION
**Pull request by bobi7**
code cleanup added

ref #1900

### CODE REVIEW

File: modules/Hoot/ui/modals/importDataset.js [hunk 1]
```diff
@@ -71,6 +69,17 @@ export default class ImportDataset {
         ];
     }
 
+    static importTypeMap() {
```
Comment (bobi7) [inline modules/Hoot/ui/modals/importDataset.js:72]: chose to add here because import multiple is using the same api logic as import single anyways so figure this would be the root

File: modules/Hoot/ui/modals/importDataset.js [hunk 2]
```diff
@@ -71,6 +69,17 @@ export default class ImportDataset {
...
+        return {
+            'DIR': null,
+            'GEONAMES': '.geonames, .txt',
+            'OSM': '.osm, .osm.zip, .pbf',
+            'FILE': '.shp, .shx, .dbf, .prj, .zip',
+            'GEOJSON': '.geojson, .geo',
```
Comment (brianhatchl) [inline modules/Hoot/ui/modals/importDataset.js]: is .geo really a valid extension for geojson?

Comment (bobi7) [reply modules/Hoot/ui/modals/importDataset.js]: it was already there before so i assume someone put it for a good reason

google says "A GEO file is a 3D CAD file saved in the GEO format"

Comment (brianhatchl) [reply modules/Hoot/ui/modals/importDataset.js]: I'd rather it be .json, can you make that switch?

Comment (brianhatchl) [reply modules/Hoot/ui/modals/importDataset.js]: .geojson and .json

Comment (bobi7) [reply modules/Hoot/ui/modals/importDataset.js]: fixed

**Review by brianhatchl — APPROVED** [review]
Nice refactoring :taco:
