### PR TITLE
Fixed #1691. fixed issue where folder wasnt closing properly on click

### LINKED ISSUE #1691: deleting folder doesnt cause datasets inside to get deleted as well

### PR DESCRIPTION
**Pull request by bobi7**
ref #1691

### CODE REVIEW

File: modules/Hoot/tools/folderTree.js [hunk 1]
```diff
@@ -782,6 +782,7 @@ export default class FolderTree extends EventEmitter {
 
                     if ( d.children ) {
                         data._children = d.children;
+                        d.children     = null;
```
Comment (bobi7) [inline modules/Hoot/tools/folderTree.js:785]: this is used by d3.tree() to see if a folders children should be displayed.

**Review by brianhatchl — APPROVED** [review]
LGTM :ping_pong:
