### PR TITLE
Fixed #1801. fixed where tm pull would use custom extent if not selected

### LINKED ISSUE #1801: TM pulls not always going to correct project folder
The folder gets its name from the comment url hash which is then kept in local storage.  I wonder if there was a failure to get the new value or somehow the pull was done without a launch from TM, but an old local storage value was still present.

### PR DESCRIPTION
**Pull request by bobi7**
ref #1801

### CODE REVIEW

File: modules/Hoot/tools/grailPull.js [hunk 1]
```diff
@@ -200,6 +201,16 @@ export default class GrailPull {
         } );
     }
 
+    // Checks if there is tm project and task info set. Also check that the custom
+    static customDataExtentEnabled() {
+        if ( sessionStorage.getItem('tm:project') && sessionStorage.getItem('tm:task') &&
+            Hoot.context.layers().layer('data').enabled() && Hoot.context.layers().layer('data').hasData() ) {
```
Comment (brianhatchl) [inline modules/Hoot/tools/grailPull.js]: This line is checking the presence of gpx task bounds data?

**Review by brianhatchl — APPROVED** [review]
LGTM :martial_arts_uniform:

File: modules/Hoot/tools/grailPull.js (hunk 1 above)
Comment (bobi7) [reply modules/Hoot/tools/grailPull.js]: yea and that its enabled just incase someone has a bounds but they dont want to use it for a pull, they can still disabled the bounds
