### PR TITLE
Fixed #1866. fixed error with running saved favorite conflation type

### LINKED ISSUE #1866: error with running saved favorite conflation type
after saving favorite options and trying to use that save set to run conflate errors occur

VGI-2324

### PR DESCRIPTION
**Pull request by bobi7**
ref #1866

### CODE REVIEW

File: modules/Hoot/ui/sidebar/advancedOpts.js [hunk 1]
```diff
@@ -848,34 +848,30 @@ export default class AdvancedOpts {
...
-                        default: d3.select(`#${member.id}`).select('input').property('checked'),
-                        id: member.id,
-                        description: member.description,
-                        label: member.label,
-                        type: member.type,
-                        option: member.option
-
-                    }
-                );
+                defaultVal = d3.select(`#${member.id}`).select('input').property('checked');
```
Comment (maxgrossman) [inline modules/Hoot/ui/sidebar/advancedOpts.js]: if the only thing that is different here is 'checked' versus 'value' could you just do a `defaultVal  = ${all that d3 stuff}.property(member.input === checkbox ? 'checked' : 'value')`

Comment (maxgrossman) [reply modules/Hoot/ui/sidebar/advancedOpts.js]: even better just assign the value in the dictionary `selectedOpt` rather than creating the variable for it

Comment (bobi7) [reply modules/Hoot/ui/sidebar/advancedOpts.js]: great idea

**Review by maxgrossman — APPROVED** [review]
tested and works as described. nice
