### PR TITLE
fixed #1718. fixed bug so folder modify name and visibility works

### LINKED ISSUE #1718: modify folder bugs with name and visibility
when a folder is set to public and modify is selected, the public checkbox should be pre-selected

cant change name of folder

### PR DESCRIPTION
**Pull request by bobi7**
ref #1718

### CODE REVIEW

File: modules/Hoot/ui/modals/modifyFolder.js [hunk 1]
```diff
@@ -88,7 +88,7 @@ export default class ModifyFolder {
             str              = node.value,
 
             reservedWords    = [ 'root', 'dataset', 'dataset', 'folder' ],
-            unallowedPattern = new RegExp( /[~`#$%\^&*+=\-\[\]\\';\./!,/{}|\\":<>\?|]/g ),
+            unallowedPattern = new RegExp( /[~`#$%\^&*+=\[\]\\';/!,/{}|\\":<>\?|]/g ),
```
Comment (bobi7) [inline modules/Hoot/ui/modals/modifyFolder.js:91]: I removed the `-` and `.` from this since the grail pull directory default name includes both of these characters

**Review by brianhatchl — APPROVED** [review]
Let's go! :checkered_flag:
