### PR TITLE
Fixed #1833. We can now split GeometryCollection into multiple features

### LINKED ISSUE #1833: export alpha shape download fails for GeometryCollection
UI doesn't have code to handle feature type GeometryCollection

### PR DESCRIPTION
**Pull request by bobi7**
ref #1833

### CODE REVIEW

File: modules/svg/data.js [hunk 1]
```diff
@@ -121,6 +122,11 @@ export function svgData(projection, context, dispatch) {
         if (!gj) return null;
 
         if (gj.type === 'FeatureCollection') {
+            // Split geometry collection into seperate features
+            if (containsGeometryCollection(gj)) {
+                geometryCollectionToFeatures(gj);
+            }
```
Comment (brianhatchl) [inline modules/svg/data.js]: I think GeometryCollection could also appear as a single feature, outside of a FeatureCollection.  It should be possible to support that too by making `geometryCollectionToFeatures` more like `ensureFeatureID` in that it takes a single feature at a time and operates on it.

**Review by brianhatchl — CHANGES_REQUESTED** [review]
This is good and works, but...

File: modules/svg/data.js [hunk 2]
```diff
@@ -161,6 +167,17 @@ export function svgData(projection, context, dispatch) {
     }
 
 
+    function containsGeometryCollection(gj) {
+        var features = getFeatures(gj);
+
+        var geomCollections = features.filter(function(feature) {
+            return feature.geometry.type === 'GeometryCollection';
+        });
```
Comment (brianhatchl) [inline modules/svg/data.js]: I think this could be made more performant by using `.some()` so that it can stop looping at the first GeometryCollection.

File: modules/svg/data.js [hunk 3]
```diff
@@ -427,6 +444,45 @@ export function svgData(projection, context, dispatch) {
...
+
+        var newFeaturesList = _reduce(currentFeatures, function(featuresAggregate, featureItem) {
+            var features = [];
+
+            if (featureItem.geometry.type === 'GeometryCollection') {
+                var geometries = featureItem.geometry.geometries;
+
+                geometries.forEach( function(geom, index) {
+                    var newFeature = _cloneDeep(featureItem);
+                    newFeature.roles = newFeature.roles.split(';')[index];
```
Comment (brianhatchl) [inline modules/svg/data.js]: So `roles` isn't really a valid geojson property and neither is `relation-type`.  Not sure we need to handle it explicitly.  Rather than a deep clone maybe just copy the `properties` property to all output features.

**Review by brianhatchl — COMMENTED** [review]
I like the approach of this refactoring, but a GeometryCollection can also have Points or LineStrings or Polygons as long as they are all the same geometry type.

File: modules/svg/data.js [hunk 4]
```diff
@@ -157,7 +157,7 @@ export function svgData(projection, context, dispatch) {
 
 
     function isPolygon(d) {
-        return d.geometry.type === 'Polygon' || d.geometry.type === 'MultiPolygon';
+        return d.geometry.type === 'Polygon' || d.geometry.type === 'MultiPolygon' || d.geometry.type === 'GeometryCollection';
```
Comment (brianhatchl) [inline modules/svg/data.js]: This will assume all GeometryCollections should be styled like areas (with the inner shading).  Might I suggest a boolean expression like this to test the types in the geometries property:
```
|| (d.geometry.type === 'GeometryCollection' && d.geometry.geometries.every(function(g) {
+            return g.type === 'Polygon' || g.type === 'MultiPolygon';
+        }))
```

File: modules/svg/data.js [hunk 5]
```diff
@@ -500,29 +500,41 @@ export function svgData(projection, context, dispatch) {
...
-                case 'MultiLineString':
-                    c = _flatten(c);
-                    break;
+            var c = [];
+            if (feature.geometry.geometries) {
+                feature.geometry.geometries.forEach( function(geom) {
+                    c = c.concat(flattenGeoms(geom.coordinates, geom.type));
+                });
+            } else {
+                c = flattenGeoms(feature.geometry.coordinates, feature.geometry.type);
```
Comment (brianhatchl) [inline modules/svg/data.js:538]: really good approach, better than turning geometry collection into feature array in the geojson

File: modules/svg/data.js [hunk 6]
```diff
@@ -500,29 +500,41 @@ export function svgData(projection, context, dispatch) {
...
+    function flattenGeoms(c, type) {
+        /* eslint-disable no-fallthrough */
+        switch (type) {
+            case 'Point':
+                c = [c];
+            case 'MultiPoint':
+            case 'LineString':
+                break;
+
+            case 'GeometryCollection':
```
Comment (brianhatchl) [inline modules/svg/data.js]: I think this case line can be deleted, as the code will now pass geometries.

File: modules/svg/data.js (hunk 4 above)
Comment (brianhatchl) [reply modules/svg/data.js]: LineStrings will appear like this:
image
vs
image

**Review by brianhatchl — CHANGES_REQUESTED** [review]
I think you nailed it :hammer: 

couple finishing suggestions

**Review by brianhatchl — APPROVED** [review]
